---
kind: pipeline
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: publish-latest
  pull: default
  image: plugins/docker
  commands:
  -  docker ps
  settings:
    context: .
    dockerfile: Dockerfile
    group: publish
    repo: rancher/docs
    password:
      from_secret: ALI_DOCKER_PASSWORD
    username:
      from_secret: ALI_DOCKER_USERNAME
  when:
    branch:
    - master
    event:
    - push
    
