---
kind: pipeline
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: publish-latest
  pull: default
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  -  docker ps
  settings:
    context: .
    dockerfile: Dockerfile
    group: publish
    repo: rancher/docs
    password:
      from_secret: ALI_DOCKER_PASSWORD
    username:
      from_secret: ALI_DOCKER_USERNAME
  when:
    branch:
    - master
    event:
    - push
services:
- name: docker
  image: docker:dind
  environment:
  - DRONE_ADMIN=xiaoluhong@rancher.com
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
