language: python
python:
  - "2.7"
dist: xenial
sudo: required
before_script:
  # Set up git user name and tag this commit
  - git config --global user.name "xiaoluhong"
  - git config --global user.email "xiaoluhong@rancher.com"
  - git config --global push.default simple

script:
  - bash start.sh

install:
  - pip install pyyaml

services:
  - docker
before_install:
  - sudo apt-get update
  - sudo pip install shyaml 
  - sudo apt-get install jq curl gettext-base sed python-yaml
  - chmod +x start.sh 
